services:
  postgres:
    image: postgres:15
    container_name: notesverb-postgres
    environment:
      POSTGRES_USER: notesverb
      POSTGRES_PASSWORD: notesverb123
      POSTGRES_DB: notesverb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    networks:
      - notesverb-network


volumes:
  postgres_data:

networks:
  notesverb-network:
    driver: bridge